// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpkmztjoujqmyjinvtnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwa216dGpvdWpxbXlqaW52dG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzE0MjcsImV4cCI6MjA2NzU0NzQyN30.DFjOkfPsuiPH2s3A_qH1pOIIiKDnx027SYxv9gtpkcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});